apps/apps/users/urls.py
from django.urls import path

from apps.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

apps/config/urls.py
#django apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

#third party apps
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenBlacklistView



#local apps
from apps.users.api.jwt import CustomTokenObtainPairView
from apps.users.api.views import RegisterView, UserViewSet
from apps.core.views import ShowData


VERSION_V1 = "api/v1/"

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    path(f"{VERSION_V1}token/", CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f"{VERSION_V1}token/refresh/", TokenRefreshView.as_view(), name='token_refresh'),
    path(f"{VERSION_V1}register/", RegisterView.as_view(), name='auth_register'),
    path(f"{VERSION_V1}logout/", TokenBlacklistView.as_view(), name='token_blacklist'),
    # API core
    path(f"{VERSION_V1}core/data/", ShowData.as_view(), name="api-schema"),
    # DRF auth token
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

router = DefaultRouter()
router.register(f"{VERSION_V1}users", UserViewSet, basename='user')

urlpatterns += router.urls


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/apps/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

apps/apps/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
      apps
    {% endblock title %}
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description"
        content="Backend for genios studios" />
  <meta name="author"
        content="Eliezer Romero" />
  <link rel="icon" href="{% static "images/Genios_ppt-11.png"%}" />
  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
          integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
<!-- Your stuff: Third-party CSS libraries go here -->
<!-- This file stores project-specific CSS -->


  <link href="{% static 'css/project.css' %}" rel="stylesheet" />


{% endblock css %}
<!-- Le javascript
    ================================================== -->
{# Placed at the top of the document so pages load faster with defer #}
{% block javascript %}


<!-- Bootstrap JS -->
<script defer
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
        integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>



  <script defer src="{% static 'js/project.js' %}"></script>


{% endblock javascript %}
</head>
<body>
  <div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler navbar-toggler-right"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Inicio <span class="visually-hidden">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link"
                   href="{% url 'users:detail' request.user.pk %}">{% translate "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
              </li>
            {% else %}
              {% if ACCOUNT_ALLOW_REGISTRATION %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                </li>
              {% endif %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="container">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
          {{ message }}
          <button type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}
    {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}
  </div>
  <!-- /container -->
  {% block modal %}
  {% endblock modal %}
  {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
    {% endcomment %}
  {% endblock inline_javascript %}
</body>
</html>